### ISSUE TITLE
-- iletişim

### ISSUE THREAD

**Issue by slayerulan** [ulaskorpe/socketio#1]
ulaş bey merhaba, mailinizi bulamadığımdan buradan ulaşıyorum,
anladığım kadarıyla ekol'ün scraperi ile ilgili çalışıyordunuz. ekol feedleri nereden çekiyor acaba bir bilginiz var mı? teşekkürler \m/

**Comment by ulaskorpe** [comment]
selamlar  , emailim ulaskorpe@gmail.com . bu socketio projesini geçen sene çalıştığım şirket için yapmıştım , şu anda nasıl çalıştırıyorlar nereden veri çekiyorlar hiç bir fikrim yok. ancak sözkonusu verinin kamuya açık olmadığını sadece belli ip ve kullanıcılar tarafından çekilebildiğini düşünüyorum

**Comment by slayerulan** [comment]
çok teşekkürler, b**radar odds feedden çekmediklerini, bet3000 gibi bir yerden çektiklerini biliyorum fakat hatırlayamıyorum o yüzden sormuştum. hatırlasaydınız çok iyi olurdu :)

bu arada kodu en azından githubda kendi isminizle koymamanızı tavsiye ederim zira şirketlere geriye dönük araştırmalarda github da kullanılmaya başladı. iyi çalışmalar \m/
